import type { ChangeEvent, FormEvent } from 'react'
import type { ProductFormValues } from '../types/product'
import { useLanguage } from '../i18n'

export interface ProductFormProps { values: ProductFormValues; editing: boolean; busy: boolean; error: string | null; onChange: (field: keyof ProductFormValues, value: string | File | null) => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; onCancel: () => void }
function FileInput({ label, preview, onChange }: { label: string; preview: string | null; onChange: (file: File | null) => void }) { const { t } = useLanguage(); return <label className="block"><span className="label">{label}</span><span className="mt-2 flex min-h-28 cursor-pointer items-center justify-center overflow-hidden rounded-2xl border border-dashed border-slate-300 bg-slate-50 text-center text-sm font-semibold text-slate-500 hover:border-teal-500">{preview ? <img src={preview} alt={t.currentUpload} className="h-32 w-full object-cover"/> : <span>{t.choose}<br/><small className="font-normal">{t.imageHint}</small></span>}<input className="sr-only" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={event => onChange(event.target.files?.[0] ?? null)}/></span></label> }

export function ProductForm({ values, editing, busy, error, onChange, onSubmit, onCancel }: ProductFormProps) {
  const change = (field: keyof ProductFormValues) => (event: ChangeEvent<HTMLInputElement>) => onChange(field, event.target.value)
  const { t } = useLanguage()
  const imagePreview = values.productImage ? URL.createObjectURL(values.productImage) : productUrl(values.image_path); const colorsPreview = values.colorsImage ? URL.createObjectURL(values.colorsImage) : productUrl(values.colors)
  return <main className="page-shell"><div className="mx-auto max-w-2xl px-4 py-6 sm:py-10"><button type="button" onClick={onCancel} className="mb-6 text-sm font-bold text-slate-600">← {t.cancel}</button><form onSubmit={onSubmit} className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm sm:p-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-teal-700">{t.inventory}</p><h1 className="mt-2 text-2xl font-bold">{editing ? t.edit : t.create}</h1><p className="mt-2 text-sm text-slate-500">{t.required}</p>
    {error && <div className="mt-5 rounded-xl bg-rose-50 p-3 text-sm font-semibold text-rose-700">{error}</div>}
    <div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label={`${t.item} *`}><input required maxLength={50} value={values.itemno} onChange={change('itemno')} className="field" placeholder={t.itemPlaceholder}/></Field><Field label={`${t.colli} (${t.optional})`}><input type="number" min="0" step="1" value={values.colli} onChange={change('colli')} className="field" placeholder="0"/></Field><Field label={`${t.buying} *`}><input required type="number" min="0" step="0.01" value={values.buying_price} onChange={change('buying_price')} className="field" placeholder="0.00"/></Field><Field label={`${t.selling} *`}><input required type="number" min="0" step="0.01" value={values.selling_price} onChange={change('selling_price')} className="field" placeholder="0.00"/></Field><div className="sm:col-span-2"><Field label={`${t.tags} (${t.optional})`}><input value={values.tags} onChange={change('tags')} className="field" placeholder={t.tagsPlaceholder}/></Field><p className="mt-1.5 text-xs text-slate-400">{t.tagHint}</p></div><FileInput label={t.productImage} preview={imagePreview} onChange={file => onChange('productImage', file)}/><FileInput label={`${t.colorImage} (${t.optional})`} preview={colorsPreview} onChange={file => onChange('colorsImage', file)}/></div>
    <div className="mt-8 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} disabled={busy} className="btn-secondary">{t.cancel}</button><button type="submit" disabled={busy} className="btn-primary">{busy ? t.saving : editing ? t.save : t.create}</button></div>
  </form></div></main>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="label">{label}</span><span className="mt-2 block">{children}</span></label> }
function productUrl(path: string | null) { return path ? `${(import.meta.env.VITE_API_URL as string | undefined) ?? ''}${path}` : null }
