"""add product notes

Revision ID: b4a46f8fe25e
Revises: 2bedaf7f1516
Create Date: 2026-07-23 14:16:27.590299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4a46f8fe25e'
down_revision: Union[str, Sequence[str], None] = '2bedaf7f1516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('notes', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'notes')
    # ### end Alembic commands ###
