/* eslint-disable react-refresh/only-export-components */
import { createContext, useContext, type ReactNode } from 'react'
export type Language = 'en' | 'zh'
const copy = {
 en: { overview:'Product overview', inventory:'Inventory', count:'products shown', newProduct:'New product', search:'Search item number or tag…', filter:'Filter', sort:'Sort products', newest:'Newest first', oldest:'Oldest first', asc:'Item no. A–Z', desc:'Item no. Z–A', item:'Item number', selling:'Selling price', buying:'Buying price', reveal:'Reveal', revealPrice:'Reveal price', noImage:'No product image', noProducts:'No products yet', empty:'Create your first product to begin building your collection.', create:'Create product', loadError:'Unable to load products', retry:'Try again', details:'Product details', back:'Back to products', created:'Created', colli:'Colli', tags:'Tags', colors:'Colors', available:'Available colors', edit:'Edit product', delete:'Delete', cancel:'Cancel', deleting:'Deleting…', confirmDelete:'Delete product', deleteCopy:'This removes the product from your inventory permanently. This action cannot be undone.', required:'Fields marked with an asterisk are required.', optional:'optional', tagHint:'Separate tags with commas.', tagsPlaceholder:'New, Bestseller, Seasonal', itemPlaceholder:'e.g. CH-2048', productImage:'Product image', colorImage:'Colors image', choose:'Choose image', currentUpload:'Current upload', imageHint:'PNG, JPG, WebP · max 5 MB', saving:'Saving…', save:'Save changes', language:'中文' },
 zh: { overview:'产品一览', inventory:'库存管理', count:'件产品', newProduct:'新增产品', search:'搜索货号或标签…', filter:'筛选', sort:'产品排序', newest:'最新创建', oldest:'最早创建', asc:'货号 A–Z', desc:'货号 Z–A', item:'货号', selling:'销售价', buying:'采购价', reveal:'显示', revealPrice:'显示价格', noImage:'暂无产品图片', noProducts:'暂无产品', empty:'创建第一个产品，开始管理您的商品。', create:'创建产品', loadError:'无法加载产品', retry:'重试', details:'产品详情', back:'返回产品列表', created:'创建于', colli:'装箱数', tags:'标签', colors:'颜色', available:'可选颜色', edit:'编辑产品', delete:'删除', cancel:'取消', deleting:'删除中…', confirmDelete:'删除产品', deleteCopy:'产品将从库存中永久删除，此操作无法撤销。', required:'带星号的字段为必填项。', optional:'选填', tagHint:'请使用逗号分隔标签。', tagsPlaceholder:'新品、畅销、季节限定', itemPlaceholder:'例如 CH-2048', productImage:'产品图片', colorImage:'颜色图片', choose:'选择图片', currentUpload:'当前上传的图片', imageHint:'PNG、JPG、WebP · 最大 5 MB', saving:'保存中…', save:'保存修改', language:'English' }
}
type Copy = typeof copy.en
const Context = createContext<{language:Language;t:Copy}>({language:'en',t:copy.en})
export function LanguageProvider({language,children}:{language:Language;children:ReactNode}) { return <Context.Provider value={{language,t:copy[language] as Copy}}>{children}</Context.Provider> }
export const useLanguage = () => useContext(Context)
